name: bruno cli CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: run tests
        run: npm run bru-test -- --env-var apiKey=${{ secrets.APIKEY }}
